
program.exe: thuyng2Proj6.o MyList.o FileList.o Island.o
	g++ -o program.exe thuyng2Proj6.o MyList.o FileList.o Island.o
thuyng2Proj6.o: thuyng2Proj6.cpp header.h
	g++ -c thuyng2Proj6.cpp
MyList.o: MyList.cpp header.h
	g++ -c MyList.cpp
FileList.o: FileList.cpp header.h
	g++ -c FileList.cpp
Island.o: Island.cpp header.h
	g++ -c Island.cpp